#!/bin/bash

# Autostart
~/.config/bspwm/scripts/00A &

bspc monitor -d I II III IV V VI

# Borderles Windows
bspc config border_width            2
bspc config window_gap              10
bspc config split_ratio             0.50
bspc config focus_follows_pointer   true

# Layout Default
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true

