#!/usr/bin/bash

# ========= STOP PROCESS ========= #
killall -q picom
killall -q polybar
killall -q dunst

# Wait until stop
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done

# ========= WALLPAPER ========= #
feh --bg-fill "$HOME/.wallpaper/Kurumi.jpg"

# ========= PICOM (ORIGINAL) ========= #
picom --experimental-backends --config "$HOME/.config/picom/picom.conf" &

# ========= POLYBAR (MULTI MONITOR) ========= #
~/.config/polybar/launch.sh &

# ========= NOTIFICATION DAEMON ========= #
/usr/bin/dunst &

# ========= POLKIT (GUI ROOT PASSWORD PROMPT) ========= #
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# ========= AUTOSTART APPS VIA DEX ========= #
dex --autostart --environment i3 &

# ========= POWER SAVING DISPLAY ========= #
xset s 480 dpms 600 600 600 &

# ========= Script Auto ========= #
# Auto handle monitor hotplug
~/.config/i3/scripts/dualmonitor &
# Auto pause/resume picom saat fullscreen
~/.config/picom/autopause.sh &

exit 0

